services:
  postgres:
    image: postgres
    container_name: datashop-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: loja
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: